export interface StateData {
  state: string;
  lgas: string[];
}

export const NIGERIA_STATES: StateData[] = [
  {
    state: "Abia",
    lgas: [
      "Aba North",
      "Aba South",
      "Arochukwu",
      "Bende",
      "Ikwuano",
      "Isiala Ngwa North",
      "Isiala Ngwa South",
      "Isuikwuato",
      "Obi Ngwa",
      "Ohafia",
      "Osisioma",
      "Ugwunagbo",
      "Ukwa East",
      "Ukwa West",
      "Umuahia North",
      "Umuahia South",
      "Umu Nneochi",
    ],
  },
  {
    state: "Adamawa",
    lgas: [
      "Demsa",
      "Fufore",
      "Ganye",
      "Gombi",
      "Hong",
      "Jimeta",
      "Madagali",
      "Mayo-Belwa",
      "Mubi",
      "Numan",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola",
      "Yola North",
      "Yola South",
    ],
  },
  {
    state: "Akwa Ibom",
    lgas: [
      "Abak",
      "Eket",
      "Etinan",
      "Ikot Abasi",
      "Ikot Ekpene",
      "Itu",
      "Mkpat Enin",
      "Oron",
      "Uruan",
      "Uyo",
    ],
  },
  {
    state: "Anambra",
    lgas: [
      "Aguata",
      "Anambra East",
      "Anambra West",
      "Anaocha",
      "Awka North",
      "Awka South",
      "Ayamelum",
      "Dunukofia",
      "Ekwusigo",
      "Idemili North",
      "Idemili South",
      "Ihiala",
      "Njikoka",
      "Nnewi North",
      "Nnewi South",
      "Ogbaru",
      "Onitsha North",
      "Onitsha South",
      "Orumba North",
      "Orumba South",
      "Oyi",
    ],
  },
  {
    state: "Bauchi",
    lgas: [
      "Alkaleri",
      "Bauchi",
      "Bogoro",
      "Damban",
      "Darazo",
      "Dass",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Itas/Gadau",
      "Jama'are",
      "Katagum",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa Balewa",
      "Toro",
      "Warji",
      "Zaki",
    ],
  },
  {
    state: "Bayelsa",
    lgas: [
      "Amassoma",
      "Brass",
      "Ekeremor",
      "Kaiama",
      "Nembe",
      "Ogbia",
      "Okolobiri",
      "Sagbama",
      "Swali",
      "Yenagoa",
    ],
  },
  {
    state: "Benue",
    lgas: [
      "Adikpo",
      "Aliade",
      "Buruku",
      "Gboko",
      "Katsina-Ala",
      "Lessel",
      "Makurdi",
      "Naka",
      "Obarike-Ito",
      "Obi",
      "Oju",
      "Otukpo",
      "Sankera",
      "Tarka",
      "Ugbokolo",
      "Ugbor",
      "Vandeikya",
      "Wannune",
      "Yandev",
      "Zaki Biam",
    ],
  },
  {
    state: "Borno",
    lgas: [
      "Abadam",
      "Askira",
      "Bama",
      "Benisheikh",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Gamboru",
      "Gubio",
      "Gwoza",
      "Hawul",
      "Jere",
      "Kaga",
      "Kukawa",
      "Magumeri",
      "Mainok",
      "Maiduguri",
      "Monguno",
      "Ngala",
      "Shani",
    ],
  },
  {
    state: "Cross River",
    lgas: [
      "Akamkpa",
      "Akpabuyo",
      "Bekwarra",
      "Biase",
      "Boki",
      "Calabar",
      "Ikom",
      "Obanliku",
      "Obubra",
      "Obudu",
      "Odukpani",
      "Ogoja",
      "Ugep",
      "Yakurr",
    ],
  },
  {
    state: "Delta",
    lgas: [
      "Agbor",
      "Asaba",
      "Bomadi",
      "Burutu",
      "Effurun",
      "Forcados",
      "Issele-Uku",
      "Koko",
      "Kwale",
      "Obiaruku",
      "Oghara",
      "Ogwashi-Uku",
      "Oleh",
      "Orerokpe",
      "Otu-Jeremi",
      "Ozoro",
      "Sapele",
      "Ughelli",
      "Warri",
    ],
  },
  {
    state: "Ebonyi",
    lgas: [
      "Abakaliki",
      "Afikpo",
      "Edda",
      "Effium",
      "Ishielu",
      "Ivo",
      "Izzi",
      "Ngbo",
      "Onicha",
      "Onueke",
    ],
  },
  {
    state: "Edo",
    lgas: [
      "Abudu",
      "Auchi",
      "Benin City",
      "Ekpoma",
      "Ehor",
      "Fugar",
      "Igarra",
      "Igueben",
      "Irrua",
      "Okada",
      "Sabongida-Ora",
      "Ubiaja",
      "Uromi",
    ],
  },
  {
    state: "Ekiti",
    lgas: [
      "Ado-Ekiti",
      "Aramoko",
      "Emure",
      "Erijiyan",
      "Ido",
      "Ijero",
      "Ikere",
      "Ikole",
      "Ilawe",
      "Ise",
      "Ode",
      "Omuo",
      "Otun",
    ],
  },
  {
    state: "Enugu",
    lgas: [
      "Abakpa",
      "Agbani",
      "Awgu",
      "Emene",
      "Enugu",
      "Nsukka",
      "Nike",
      "Ngwo",
      "Ninth Mile",
      "Oji River",
      "Trans Ekulu",
      "Udi",
      "Uwani",
    ],
  },
  {
    state: "Gombe",
    lgas: [
      "Akko",
      "Bajoga",
      "Billiri",
      "Deba",
      "Dukku",
      "Gombe",
      "Kaltungo",
      "Kumo",
      "Nafada",
      "Shongom",
      "Tula",
      "Yamaltu-Deba",
    ],
  },
  {
    state: "Imo",
    lgas: [
      "Aboh Mbaise",
      "Ehime Mbano",
      "Mbaise",
      "Ngor Okpala",
      "Nkwerre",
      "Oguta",
      "Okigwe",
      "Orlu",
      "Owerri",
      "Owerri North",
      "Owerri West",
      "Ozubulu",
      "Ubulu",
    ],
  },
  {
    state: "Jigawa",
    lgas: [
      "Babura",
      "Birnin Kudu",
      "Birniwa",
      "Dutse",
      "Gagarawa",
      "Gumel",
      "Guri",
      "Gwaram",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Kazaure",
      "Kiyawa",
      "Maigatari",
      "Malam Madori",
      "Ringim",
      "Taura",
    ],
  },
  {
    state: "Kaduna",
    lgas: [
      "Barnawa",
      "Chikun",
      "Gonin Gora",
      "Kachia",
      "Kaduna",
      "Kaduna North",
      "Kaduna South",
      "Kafanchan",
      "Kajuru",
      "Kakuri",
      "Kawo",
      "Kurmin Mashi",
      "Makarfi",
      "Malali",
      "Mando",
      "Narayi",
      "Rigachikun",
      "Sabon Tasha",
      "Sabo",
      "Television",
      "Trikania",
      "Tudun Wada",
      "Ungwan Boro",
      "Ungwan Dosa",
      "Ungwan Rimi",
      "Zaria",
    ],
  },
  {
    state: "Kano",
    lgas: [
      "Dala",
      "Dawakin Kudu",
      "Dawakin Tofa",
      "Fagge",
      "Gaya",
      "Gezawa",
      "Gwarzo",
      "Hotoro",
      "Kano",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Naibawa",
      "Nasarawa",
      "Rano",
      "Sabon Gari",
      "Sharada",
      "Tarauni",
      "Tofa",
      "Ungogo",
      "Wudil",
    ],
  },
  {
    state: "Katsina",
    lgas: [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Daura",
      "Dutsin-Ma",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kankara",
      "Kankia",
      "Katsina",
      "Malumfashi",
      "Mani",
      "Mashi",
      "Musawa",
      "Rimi",
      "Safana",
    ],
  },
  {
    state: "Kebbi",
    lgas: [
      "Aliero",
      "Argungu",
      "Bagudo",
      "Birnin Kebbi",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Jega",
      "Koko",
      "Mahuta",
      "Shanga",
      "Wasagu",
      "Yauri",
      "Zuru",
    ],
  },
  {
    state: "Kogi",
    lgas: [
      "Ajaokuta",
      "Ankpa",
      "Dekina",
      "Idah",
      "Ife-Olukotun",
      "Isanlu",
      "Kabba",
      "Koton Karfe",
      "Lokoja",
      "Mopa",
      "Obajana",
      "Ogori",
      "Okene",
      "Olamaboro",
      "Omala",
    ],
  },
  {
    state: "Kwara",
    lgas: [
      "Ajase-Ipo",
      "Bode Saadu",
      "Erin-Ile",
      "Ilorin",
      "Jebba",
      "Kaiama",
      "Lafiagi",
      "Offa",
      "Oke-Oyi",
      "Omu-Aran",
      "Patigi",
      "Share",
    ],
  },
  {
    state: "Lagos",
    lgas: [
      "Abule Egba",
      "Agege",
      "Ajah",
      "Ajegunle",
      "Alagbado",
      "Alimosho",
      "Amuwo Odofin",
      "Anthony",
      "Apapa",
      "Badagry",
      "Banana Island",
      "Bariga",
      "Chevron",
      "Dopemu",
      "Ebute Metta",
      "Epe",
      "Festac Town",
      "Gbagada",
      "Ibeju-Lekki",
      "Idimu",
      "Ifako-Ijaiye",
      "Igando",
      "Ikeja",
      "Ikorodu",
      "Ikota",
      "Ikoyi",
      "Ilupeju",
      "Iyana Ipaja",
      "Lagos Island",
      "Lekki",
      "Magodo",
      "Maryland",
      "Mushin",
      "Ogba",
      "Ojodu",
      "Ojo",
      "Onikan",
      "Oniru",
      "Oregun",
      "Oshodi",
      "Sangotedo",
      "Shomolu",
      "Surulere",
      "Victoria Island",
      "Yaba",
    ],
  },
  {
    state: "Nasarawa",
    lgas: [
      "Akwanga",
      "Awe",
      "Doma",
      "Keffi",
      "Kokona",
      "Lafia",
      "Masaka",
      "Nasarawa",
      "Nasarawa Eggon",
      "Obi",
      "Toto",
      "Wamba",
    ],
  },
  {
    state: "Niger",
    lgas: [
      "Agaie",
      "Baro",
      "Bida",
      "Borgu",
      "Bosso",
      "Kontagora",
      "Lapai",
      "Mokwa",
      "New Bussa",
      "Paikoro",
      "Suleja",
      "Tegina",
      "Wawa",
      "Wushishi",
    ],
  },
  {
    state: "Ogun",
    lgas: [
      "Abeokuta",
      "Ado-Odo",
      "Agbara",
      "Atan",
      "Ayetoro",
      "Ifo",
      "Ijebu-Igbo",
      "Ijebu-Ode",
      "Ikenne",
      "Ilaro",
      "Imeko",
      "Mowe",
      "Ota",
      "Owode",
      "Sagamu",
      "Sango Ota",
      "Shagamu",
    ],
  },
  {
    state: "Ondo",
    lgas: [
      "Akoko",
      "Akure",
      "Idanre",
      "Ifon",
      "Igbokoda",
      "Iju",
      "Ikare-Akoko",
      "Ile-Oluji",
      "Irele",
      "Odigbo",
      "Okitipupa",
      "Ondo",
      "Owo",
      "Owole",
      "Ore",
      "Owo",
      "Ugbo",
    ],
  },
  {
    state: "Osun",
    lgas: [
      "Aiyedire",
      "Apomu",
      "Ejigbo",
      "Ede",
      "Gbongan",
      "Ife",
      "Ikire",
      "Ikirun",
      "Ila Orangun",
      "Ilesa",
      "Ilobu",
      "Inisa",
      "Ipetumodu",
      "Iwo",
      "Iwo",
      "Modakeke",
      "Okuku",
      "Osogbo",
    ],
  },
  {
    state: "Oyo",
    lgas: [
      "Afijio",
      "Akinyele",
      "Atiba",
      "Atisbo",
      "Eruwa",
      "Egbeda",
      "Fiditi",
      "Ibadan",
      "Ibarapa Central",
      "Ibarapa East",
      "Ibarapa North",
      "Iseyin",
      "Itesiwaju",
      "Irepo",
      "Iwajowa",
      "Kishi",
      "Lagelu",
      "Lalupon",
      "Ogbomoso",
      "Ogo Oluwa",
      "Olorunsogo",
      "Ona Ara",
      "Orelope",
      "Oyo",
      "Saki",
      "Surulere",
      "Ido",
      "Ilora",
      "Moniya",
      "Oluyole",
    ],
  },
  {
    state: "Plateau",
    lgas: [
      "Barikin Ladi",
      "Bassa",
      "Bokkos",
      "Jos",
      "Jos East",
      "Jos North",
      "Jos South",
      "Kanke",
      "Kanam",
      "Lantang",
      "Langtang North",
      "Langtang South",
      "Mangu",
      "Pankshin",
      "Riyom",
      "Shendam",
      "Wase",
      "Barkin Ladi",
      "Chakwai",
      "Fobur",
      "Gyel",
      "Jingre",
      "Keffi",
      "Miango",
      "Vom",
    ],
  },
  {
    state: "Rivers",
    lgas: [
      "Abonnema",
      "Ahoada",
      "Bori",
      "Bonny",
      "Bugama",
      "Degema",
      "Elele",
      "Eleme",
      "Emohua",
      "Isiokpo",
      "Khana",
      "Omoku",
      "Oyigbo",
      "Port Harcourt",
      "Rumuodara",
      "Rumuokoro",
      "Rumuokwuta",
      "Rumuola",
      "Tai",
      "Woji",
    ],
  },
  {
    state: "Sokoto",
    lgas: [
      "Binji",
      "Bodinga",
      "Dange",
      "Dankura",
      "Gada",
      "Goronyo",
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Isa",
      "Kebbe",
      "Kware",
      "Rabah",
      "Sabon Birni",
      "Sokoto",
      "Silame",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamakko",
      "Wurno",
      "Yabo",
    ],
  },
  {
    state: "Taraba",
    lgas: [
      "Ardo-Kola",
      "Bali",
      "Baissa",
      "Donga",
      "Gembu",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Jalingo",
      "Karim Lamido",
      "Lau",
      "Maihula",
      "Mutum Biyu",
      "Takum",
      "Ussa",
      "Wukari",
      "Yorro",
      "Zing",
    ],
  },
  {
    state: "Yobe",
    lgas: [
      "Bade",
      "Bursari",
      "Damaturu",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nagere",
      "Nguru",
      "Potiskum",
      "Sabon Garin Nangere",
      "Tarmuwa",
      "Yunusari",
      "Yusufari",
    ],
  },
  {
    state: "Zamfara",
    lgas: [
      "Anka",
      "Bakura",
      "Bungudu",
      "Birnin Magaji",
      "Chafe",
      "Dan Sadau",
      "Dauran",
      "Faskari",
      "Gaura",
      "Gasau",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Maradun",
      "Maru",
      "Moriki",
      "Shinkafi",
      "Talata Mafara",
      "Tsafe",
      "Yankara",
      "Zurmi",
    ],
  },
  {
    state: "Abuja",
    lgas: [
      "Abaji",
      "Abuja",
      "Asokoro",
      "Bwari",
      "Central Area",
      "Dei-Dei",
      "Dutse",
      "Galadimawa",
      "Garki",
      "Gwarinpa",
      "Gwagwalada",
      "Idu",
      "Jabi",
      "Jahi",
      "Karmo",
      "Kubwa",
      "Kuje",
      "Lugbe",
      "Life Camp",
      "Lokogoma",
      "Mabushi",
      "Maitama",
      "Mararaba",
      "Mpape",
      "Nyanya",
      "Pai",
      "Rubochi",
      "Sabo-Wuse",
      "Wuse",
      "Wuse 2",
      "Zuba",
    ],
  },
];

export const STATE_NAMES = NIGERIA_STATES.map((s) => s.state);

export function getLGAs(stateName: string): string[] {
  return NIGERIA_STATES.find((s) => s.state === stateName)?.lgas ?? [];
}
