"use client";
import { useEffect, useRef, useState } from "react";
import { BOOKING_DURATIONS, type BookingRate, type BookingDurationId } from "@/lib/bookingRates";

const formatAmount = (value: number | string | undefined) => { if (value === undefined || value === "") return ""; const number = Number(String(value).replace(/,/g, "")); return Number.isFinite(number) ? number.toLocaleString("en-NG", { maximumFractionDigits: 2 }) : ""; };

export default function BookingRatesEditor({ value, onChange }: { value: BookingRate[]; onChange: (value: BookingRate[]) => void }) {
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const refs = useRef<Record<string, HTMLDivElement | null>>({});
  useEffect(() => setDrafts((old) => { const next = { ...old }; value.forEach((rate) => (["incall", "outcall"] as const).forEach((service) => { const key = `${rate.duration}-${service}`; next[key] = old[key] ?? formatAmount(rate[service]); })); return next; }), [value]);
  const toggle = (duration: BookingDurationId) => { const exists = value.some((rate) => rate.duration === duration); onChange(exists ? value.filter((rate) => rate.duration !== duration) : [...value, { duration }]); if (!exists) setTimeout(() => refs.current[duration]?.scrollIntoView({ behavior: "smooth", block: "center" }), 50); };
  const update = (duration: BookingDurationId, service: "incall" | "outcall", input: string) => { const raw = input.replace(/,/g, "").replace(/[^0-9.]/g, ""); const amount = raw ? Number(raw) : undefined; setDrafts((old) => ({ ...old, [`${duration}-${service}`]: raw ? formatAmount(raw) : "" })); onChange(value.map((rate) => rate.duration === duration ? { ...rate, [service]: Number.isFinite(amount) ? amount : undefined } : rate)); };
  const inputClass = "mt-1 w-full rounded-xl border border-[#CBD5E1] px-3 py-2.5 text-sm outline-none transition focus:border-[#3B82F6] focus:ring-3 focus:ring-[#3B82F6]/15";
  return <div className="space-y-4"><div className="rounded-2xl border border-blue-100 bg-blue-50/60 p-4 text-sm text-slate-700"><p className="font-semibold text-slate-900">Set your booking rates</p><p className="mt-1 leading-5">Choose durations and add at least one rate for each. Incall means the guest comes to your location; Outcall means you travel to theirs. Prices are in Nigerian Naira.</p></div><div className="grid grid-cols-2 gap-2">{BOOKING_DURATIONS.map((item) => { const selected = value.some((rate) => rate.duration === item.id); return <button type="button" key={item.id} onClick={() => toggle(item.id)} className={`rounded-xl border p-3 text-left transition ${selected ? "border-blue-700 bg-blue-50" : "border-slate-200 bg-white hover:border-blue-300"}`}><div className="flex items-center justify-between gap-2"><span className="font-semibold text-slate-900">{item.label}</span><span className={`flex h-4 w-4 shrink-0 items-center justify-center rounded-full border ${selected ? "border-blue-700" : "border-slate-300"}`}>{selected && <span className="h-2 w-2 rounded-full bg-blue-700" />}</span></div><p className="mt-1 text-xs text-slate-500">{item.description}</p></button>; })}</div>{value.map((rate) => <div ref={(element) => { refs.current[rate.duration] = element; }} key={rate.duration} className="rounded-2xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><h4 className="font-semibold text-slate-900">{BOOKING_DURATIONS.find((duration) => duration.id === rate.duration)?.label}</h4><button type="button" onClick={() => toggle(rate.duration)} className="text-xs font-semibold text-rose-600">Remove</button></div><div className="grid gap-3 sm:grid-cols-2">{(["incall", "outcall"] as const).filter((service) => rate.duration !== "travel_trips" || service === "outcall").map((service) => <label key={service} className="text-xs font-medium capitalize text-slate-600">{rate.duration === "travel_trips" ? "Starting rate" : service} (₦)<input type="text" inputMode="decimal" value={drafts[`${rate.duration}-${service}`] ?? formatAmount(rate[service])} onChange={(event) => update(rate.duration, service, event.target.value)} placeholder="Optional" className={inputClass} /></label>)}</div></div>)}{!value.length && <p className="text-sm text-amber-700">Select at least one booking duration to continue.</p>}</div>;
}
